### ISSUE TITLE
TLS is implemented but not actually used

### ISSUE THREAD

**Issue by ebr** [sendgridlabs/loggly-docker#16]
TLS support is enabled in `rsyslog.conf`, but communication with Loggly still happens over port 514 and is not encrypted. This is likely because TLS support is enabled *after* the line that enables sending everything to Loggly.

**Comment by ebr** [comment]
@jonathan-short should this also be an option? I don't see anyone **wanting** to disable TLS on purpose. But LMK.

**Comment by jonathan-short** [comment]
I merged as-is without an option to disable; we can keep an eye out for feedback.  Thanks!
