### ISSUE TITLE
Sending logs over tcp causes exit

### ISSUE THREAD

**Issue by wr0ngway** [sendgridlabs/loggly-docker#19]
If I start the container with:

```docker run --rm -p 1514:514/tcp --name loggly-docker -e LOGGLY_AUTH_TOKEN=my-token -e LOGGLY_TAG=DockerDev -e LOGGLY_DEBUG=true sendgridlabs/loggly-docker```

Then send a log over tcp:

```echo netcat:"Host test log" | nc -w 1 192.168.99.100 1514```

The container exits without any error messages.

I need to use tcp instead of udp in order to run multiple loggly containers in ECS behind ELB

**Comment by wr0ngway** [comment]
Note, if I use udp instead of tcp, the container doesn't exit, but my log message never makes it into loggly

    docker run --rm -p 1514:514/udp --name loggly-docker -e LOGGLY_AUTH_TOKEN=my-token -e LOGGLY_TAG=DockerDev -e LOGGLY_DEBUG=true sendgridlabs/loggly-docker
    echo netcat:"Host test log" | nc -u -w 1 192.168.99.100 1514

**Comment by wr0ngway** [comment]
Looks like rsyslog is segfaulting when receiving tcp data, not sure why

**Comment by wr0ngway** [comment]
If I comment out the two udp lines at the bottom of rsyslog.conf, then receiving logs over tcp works:

    #$ModLoad imudp         # provides UDP syslog reception
    #$UDPServerRun 514      # start a UDP syslog server at standard port 514

**Comment by jonathan-short** [comment]
Can't explain why, but when I load imudp prior to imtcp, the seg fault goes away and container behaves properly for both tcp and udp, accepting and sending to loggly.

Can you try sendgridlabs/loggly-docker:1.4 and let me know that it works for you too?  If all is good I will tag it latest.

**Comment by wr0ngway** [comment]
Yup, that seems to fix the problem, thanks!

**Comment by jonathan-short** [comment]
Thanks for the report! I updated the latest tag.
