### ISSUE TITLE
Feature: Support for multiple TAG values

### ISSUE THREAD

**Issue by dmulter** [sendgridlabs/loggly-docker#5]
It would be nice to allow passing of more than one TAG value that would translate into multiple TAG= values passed in the log template via 50-default.conf.

**Comment by vladgh** [comment]
+1

**Comment by jonathan-short** [comment]
Multiple tags now accepted, separated by :

**Comment by alex88** [comment]
Would be great to have that in the docs

**Comment by aprudnikoff** [comment]
Agree with @alex88. It need to be added to docs. I was seeking for this for almost an hour.
